targets:
  _expression:
    sources:
      - lib/src/models/expression.dart
      - lib/src/models/parameter.dart
  _function:
    dependencies:
      - ":_expression"
    sources:
      - lib/src/models/function.dart
  $default:
    dependencies:
      - ":_function"
    sources:
      - lib/src/models/program.dart