name: ml
version: 0.0.0
author: Tobechukwu Osakwe <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/ml
description:
  >
    A small, fast machine learning library for Dart that uses WebGL and native extensions for optimized performance.
environment:
  sdk: ">=2.0.0-dev.61 <3.0.0"
dependencies:
  angel_serialize: ^2.0.0
  c_builder: ^1.0.0
  code_buffer: ^1.0.0
  stream_channel: ^1.0.0
  symbol_table: ^1.0.0
dev_dependencies:
  angel_serialize_generator: ^2.0.0
  build_runner: ^0.9.0
  #build_web_compilers: ^0.4.0
  test: ^1.0.0